insert into product (id, product_name, description) values (1, 'Name 1', 'Description 1');
insert into product (id, product_name, description) values (2, 'Name 2', 'Description 2');
insert into product (id, product_name, description) values (3, 'Name 3', 'Description 3');
insert into product (id, product_name, description) values (4, 'Name 4', 'Description 4');
insert into product (id, product_name, description) values (5, 'Name 5', 'Description 5');
insert into product (id, product_name, description) values (6, 'Name 6', 'Description 6');
insert into product (id, product_name, description) values (7, 'Name 7', 'Description 7');
insert into product (id, product_name, description) values (8, 'Name 8', 'Description 8');
insert into product (id, product_name, description) values (9, 'Name 9', 'Description 9');
insert into product (id, product_name, description) values (10, 'Name 10', 'Description 10');
insert into reviews (id, product_id, review) values (1, 1, 'Review 1');
insert into reviews (id, product_id, review) values (2, 1, 'Review 2');
insert into reviews (id, product_id, review) values (3, 2, 'Review 3');
insert into reviews (id, product_id, review) values (4, 2, 'Review 4');
insert into reviews (id, product_id, review) values (5, 3, 'Review 5');
insert into reviews (id, product_id, review) values (6, 3, 'Review 6');
insert into reviews (id, product_id, review) values (7, 4, 'Review 7');
insert into reviews (id, product_id, review) values (8, 4, 'Review 8');
insert into reviews (id, product_id, review) values (9, 5, 'Review 9');
insert into reviews (id, product_id, review) values (10, 5, 'Review 10');
insert into reviews (id, product_id, review) values (11, 6, 'Review 11');
insert into reviews (id, product_id, review) values (12, 6, 'Review 12');
insert into reviews (id, product_id, review) values (13, 7, 'Review 13');
insert into reviews (id, product_id, review) values (14, 7, 'Review 14');
insert into reviews (id, product_id, review) values (15, 8, 'Review 15');
insert into reviews (id, product_id, review) values (16, 8, 'Review 16');
insert into reviews (id, product_id, review) values (17, 9, 'Review 17');
insert into reviews (id, product_id, review) values (18, 9, 'Review 18');
insert into reviews (id, product_id, review) values (19, 10, 'Review 19');
insert into reviews (id, product_id, review) values (20, 10, 'Review 20');