CREATE TABLE PRODUCT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(400) NOT NULL,
    description VARCHAR(1000) NOT NULL
);

CREATE TABLE REVIEWS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL,
    description VARCHAR(1000) NOT NULL
);

ALTER TABLE REVIEWS ADD CONSTRAINT reviews_product_id FOREIGN KEY (product_id) REFERENCES PRODUCT(id)